services:
  registry: salaboy
  frontend: 
    image: frontend-go-1739aa83b5e69d4ccb8a5615830ae66c@sha256
    tag: df6f60b22ffd64b23ae92e89170692db6014b95b335f990cb2023bd9cc7a8d93
  agenda: 
    image: agenda-service-0967b907d9920c99918e2b91b91937b3@sha256
    tag: ce9ce8293e4e062404226993b469a7d8dd28bd42431127d38fec5cb2da626b7d
  c4p: 
    image: c4p-service-a3dc0474cbfa348afcdf47a8eee70ba9@sha256
    tag: b44504fcc345e2ea7bc5b0bce93192c7b58a5fe69cc986e27c1a2d77e6a5c8a3
  notifications: 
    image: notifications-service-0e27884e01429ab7e350cb5dff61b525@sha256
    tag: 799c35f9f306e54a3b20a85adf83fa91dfc976665fbca7fe6ffabd314636094f
install:
  infrastructure: true
  ingress: true
postgresql:
  image:
    debug: true
  primary: 
    initdb:
      user: postgres
      password: postgres
      scriptsConfigMap: c4p-init-sql
  global:
    postgresql:
      auth: 
        postgresPassword: postgres
redis: 
  architecture: standalone
kafka: 
  provisioning:
    topics:
    - name: events-topic
      partitions: 1