apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend-go
spec:
  template:
    metadata:
      annotations:  
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containerConcurrency: 0
      containers:
        - image: ko://github.com/salaboy/platforms-on-k8s/conference-application/frontend-go
          name: user-container
          env: 
          - name: AGENDA_SERVICE_URL
            value: http://agenda-service.default.svc.cluster.local
          - name: C4P_SERVICE_URL
            value: http://c4p-service.default.svc.cluster.local  
          livenessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
          readinessProbe:
            httpGet:
              path: /health/liveness
              port: 8080