apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: conference-app-helm-chart-pipeline
  annotations:
    description: |
      Build the artifacts for the Conference application's services
spec:
  params:
    - name: gitRepository
      description: The git repository that hosts the source code of the service
      default: https://github.com/salaboy/platforms-on-k8s/
    - name: gitRevision
      description: The git revision to build
      default: main
    - name: context
      description: The path to the docker context in the sources workspace
      default: /
    - name: target-registry
      description: The target container registry and path where to build the image
      default: docker.io/salaboy
    - name: target-name
      description: Name of the image to publish
      default: your-service
    - name: target-version
      description: the target version to build
      default: 1.0.0-service-pipeline
  workspaces:
    - name: sources
      description: Workspace where the git repo is prepared for building
    - name: dockerconfig
      description: Docker config secret
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.gitRepository)
        - name: revision
          value: main
      workspaces:
        - name: output
          workspace: sources
    - name: helm-package
      runAfter: [clone-repo]
      workspaces:
        - name: dockerconfig
          workspace: dockerconfig  
        - name: sources
          workspace: sources
          subPath: "conference-application/helm/conference-app/"
      taskSpec:
        workspaces:
          - name: sources
          - name: dockerconfig
        steps:
          - name: package
            image: alpine/helm:3.11.1
            script: |
              #!/bin/sh
              set -ex 
              cd $(workspaces.sources.path)
              helm repo add bitnami https://charts.bitnami.com/bitnami
              helm repo update
              helm dependency build
              helm package .
              helm push conference-app-v1.0.0.tgz oci://docker.io/salaboy/