apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-agenda-service-deployment
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: agenda-service
  template:
    metadata:
      labels:
        app: agenda-service
    spec:
      containers:
      - name: agenda-service
        image: salaboy/agenda-service-0967b907d9920c99918e2b91b91937b3@sha256:e77e183d8d4510ef3c01cbc39dbb4ae54262f34795ed4aa71ffb529b0d6b802b
        env:
        - name: KAFKA_URL
          value: http://kafka.{{ .Release.Namespace }}.svc.cluster.local
        - name: REDIS_HOST
          value: {{ .Release.Name }}-redis-master.{{ .Release.Namespace }}.svc.cluster.local
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-redis
              key: redis-password
        livenessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
        readinessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: agenda-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: agenda-service
  ports:
  - port: 80
    targetPort: 8080
