apiVersion: v2
description: A Helm chart for the Conference App
name: conference-app-k8s
version: v1.0.0
type: application
icon: https://www.salaboy.com/content/images/2023/06/avatar-new.png
appVersion: v1.0.0
maintainers: 
  - name: salaboy
    email: salaboy@gmail.com
    url: http://salaboy.com
home: http://github.com/salaboy/platforms-on-k8s
dependencies:
- name: redis
  version: 17.11.3 
  repository: https://charts.bitnami.com/bitnami
  condition: install.infrastructure
- name: postgresql
  version: 12.5.7 
  repository: https://charts.bitnami.com/bitnami
  condition: install.infrastructure
- name: kafka
  version: 22.1.5
  repository: https://charts.bitnami.com/bitnami
  condition: install.infrastructure  
- name: nginx-ingress-controller
  version: 9.7.2
  repository: https://charts.bitnami.com/bitnami
  condition: install.ingress  
keywords:
  - cloudnative
  - platform-engineering
  - platforms
  - book
  - kubernetes
  - tutorial
  - example