apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend-deployment
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.services.registry }}/{{ .Values.services.frontend.image }}:{{ .Values.services.frontend.tag }}"
        env: 
        - name: AGENDA_SERVICE_URL
          value: http://agenda-service.{{ .Release.Namespace }}.svc.cluster.local
        - name: C4P_SERVICE_URL
          value: http://c4p-service.{{ .Release.Namespace }}.svc.cluster.local
        - name: NOTIFICATIONS_SERVICE_URL
          value: http://notifications-service.{{ .Release.Namespace }}.svc.cluster.local  
        - name: KAFKA_URL
          value: {{ .Release.Name }}-kafka.{{ .Release.Namespace }}.svc.cluster.local  
        livenessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
        readinessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 8080