apiVersion: lifecycle.keptn.sh/v1alpha3
kind: KeptnTaskDefinition
metadata:
  name: stdout-notification
  namespace: {{ .Release.Namespace }}
spec:
  function:
    inline:
      code: |
        let context = Deno.env.get("CONTEXT");
        console.log(context);
