apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-notifications-service-deployment
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      containers:
      - name: notifications-service
        image: "{{ .Values.services.registry }}/{{ .Values.services.notifications.image }}:{{ .Values.services.notifications.tag }}"
        env:
        - name: KAFKA_URL
          value: {{ .Release.Name }}-kafka.{{ .Release.Namespace }}.svc.cluster.local
              
        livenessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
        readinessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: notifications-service
  ports:
  - port: 80
    targetPort: 8080